"""Make HuggingFace reachable on a machine whose TLS is being intercepted.

THE PROBLEM (05-stage0-log.md S0 recorded it; this module is the fix)
---------------------------------------------------------------------
Stage 0 could not download any model.  Diagnosed here: the machine runs Avast,
whose Web/Mail Shield terminates every TLS connection and re-signs it.  The
certificate huggingface.co presents is therefore issued by

    CN=Avast Web/Mail Shield Root, OU=generated by Avast Antivirus for SSL/TLS scanning

and that root, which lives in both LocalMachine\\Root and CurrentUser\\Root, is
MALFORMED:

    basicConstraints   critical=False   ca=True

RFC 5280 S4.2.1.9 requires basicConstraints to be marked critical in a CA
certificate.  OpenSSL 3.x enforces that and refuses the chain with

    [SSL: CERTIFICATE_VERIFY_FAILED] Basic Constraints of CA cert not marked critical

Windows' own verifier (Schannel) does not enforce it, which is why browsers on
this machine work fine while Python does not.

WHAT DOES NOT WORK
------------------
Exporting the Avast root and appending it to certifi's bundle.  Tried and
verified: the failure is not "this CA is untrusted", it is "this CA is
malformed", so trusting it harder changes nothing.

WHAT THIS MODULE DOES
---------------------
Routes Python's TLS verification through the OPERATING SYSTEM's verifier via
the `truststore` package, instead of through OpenSSL's bundled logic.  Verified
working: huggingface.co returns 200 and the model API resolves.

This is NOT `verify=False` and it is NOT a security downgrade.  Certificates
are still verified, hostnames are still checked, and an untrusted or expired
certificate is still rejected -- the check is simply performed by the same
Windows component that Edge and Chrome use, which tolerates this one
non-critical-extension defect.  The clean fix remains disabling Avast's HTTPS
scanning; this makes the project usable without asking the user to weaken their
antivirus.

Set FISHERRAO_NO_TRUSTSTORE=1 to skip it (e.g. on a machine with no
interception, or to reproduce the original failure).
"""

from __future__ import annotations

import os

_state: str | None = None


def enable() -> str:
    """Install the OS certificate verifier.  Idempotent; returns a status string."""
    global _state
    if _state is not None:
        return _state

    if os.environ.get("FISHERRAO_NO_TRUSTSTORE"):
        _state = "skipped (FISHERRAO_NO_TRUSTSTORE set)"
        return _state
    if os.environ.get("HF_HUB_OFFLINE"):
        # Nothing will be fetched anyway; leave TLS untouched so an offline run
        # is byte-identical to what Stage 0 reproduced.
        _state = "skipped (HF_HUB_OFFLINE set)"
        return _state

    try:
        import truststore

        truststore.inject_into_ssl()
        _state = "OS verifier active (truststore)"
    except ImportError:
        _state = ("truststore not installed -- downloads will fail behind TLS "
                  "interception; pip install truststore")
    except Exception as exc:                                  # noqa: BLE001
        _state = f"truststore failed to install: {exc!r}"
    return _state


def check(host: str = "huggingface.co", timeout: float = 20.0) -> dict:
    """Report whether `host` is reachable, and if not, who is intercepting.

    Returns the issuer of the presented certificate either way, so a failure
    report names the culprit instead of just saying 'TLS error'.
    """
    import socket
    import ssl
    import urllib.request

    out: dict = dict(host=host, truststore=enable())
    try:
        urllib.request.urlopen(f"https://{host}", timeout=timeout)
        out["reachable"] = True
    except Exception as exc:                                  # noqa: BLE001
        out["reachable"] = False
        out["error"] = f"{type(exc).__name__}: {exc}"

    try:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE
        with socket.create_connection((host, 443), timeout=timeout) as sock:
            with ctx.wrap_socket(sock, server_hostname=host) as tls:
                der = tls.get_unverified_chain()[0]
        from cryptography import x509

        out["issuer"] = x509.load_der_x509_certificate(der).issuer.rfc4514_string()
        out["intercepted"] = "Avast" in out["issuer"] or "Shield" in out["issuer"]
    except Exception as exc:                                  # noqa: BLE001
        out["issuer"] = f"could not inspect: {exc!r}"
    return out


if __name__ == "__main__":
    for k, v in check().items():
        print(f"{k:>12} : {v}")
